services:
  ffc-grants-eligibility-checker:
    build:
      context: .
      target: development
    depends_on:
      - redis
    image: ffc-grants-eligibility-checker-development
    # platform: ${PLATFORM}
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      REDIS_HOSTNAME: redis # Use the Docker service name to connect
      REDIS_PASSWORD: '' # Add if needed
      SESSION_CACHE_TTL: 3600000

  reverse-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - '80:80' # Expose port 80 on the host and forward to Nginx
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf # Mount your custom Nginx config
      - ./nginx_logs:/var/log/nginx # Mount Nginx logs to host machine
    depends_on:
      - ffc-grants-eligibility-checker

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - '6383:6379'

volumes:
  redis_data:
