services:
  ffc-grants-eligibility-checker:
    build:
      context: .
      target: production
    image: ffc-grants-eligibility-checker
    # platform: ${PLATFORM}
    environment:
      NODE_ENV: production
