services:
  ffc-grants-eligibility-checker:
    build:
      context: .
      target: production
    image: ffc-grants-eligibility-checker
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      SESSION_CACHE_TTL: 3600000
      COOKIE_PASSWORD: thisistestcookiepasswordthisistestcookiepasswordthisistestcookiepassword
      USE_REDIS: true
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      REDIS_PORT: 6379
      REDIS_PARTITION: ffc-grants-eligibility-checker
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      LOCAL: ${LOCAL}
      SERVICE_BUS_HOST: ${SERVICE_BUS_HOST}
      NOTIFY_EMAIL_TEMPLATE: ${NOTIFY_EMAIL_TEMPLATE}
      NOTIFY_SUBMIT_QUEUE: ${NOTIFY_SUBMIT_QUEUE}
      NOTIFY_EMAIL_ADDRESS: ${NOTIFY_EMAIL_ADDRESS}
