version: '3.9'

services:
  ffc-grants-eligibility-checker:
    build:
      context: .
      target: production
    image: ffc-grants-eligibility-checker  
    environment:
      NODE_ENV: production
      SITE_URL: localhost:3000

