services:
  ffc-grants-eligibility-checker:
    build:
      context: .
      target: production
    image: ffc-grants-eligibility-checker
    # platform: ${PLATFORM}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - ffc-grants-eligibility-checker-network

networks:
  ffc-grants-eligibility-checker-network:
    name: "ffc-grants-eligibility-checker-network"