services:
  ffc-grants-eligibility-checker:
    ports:
      - "3001:3001"
    volumes:
      - ./test-output/:/home/node/test-output/

  axe:
    build: ./test/accessibility
    depends_on:
      - ffc-grants-eligibility-checker
      - selenium-axe
    environment:
      TEST_ENVIRONMENT_ROOT_URL: http://ffc-grants-eligibility-checker:3000
      CHROME_ARGS: "--headless --ignore-certificate-errors"
    volumes:
      - ./test-output:/home/node/test-output

  selenium-axe:
    image: selenium/standalone-chrome
    # change to following image for ARM architectures
    #image: seleniarm/standalone-chromium
    container_name: selenium-axe
    depends_on:
      - ffc-grants-eligibility-checker
    volumes:
      - /dev/shm:/dev/shm
