{{- include "ffc-helm-library.azure-identity-binding" (list . "ffc-grants-eligibility-checker.azure-identity-binding") -}}
{{- define "ffc-grants-eligibility-checker.azure-identity-binding" -}}
{{- end -}}