{{- include "ffc-helm-library.container-config-map" (list . "ffc-grants-eligibility-checker.config-map") -}}
{{- define "ffc-grants-eligibility-checker.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}  
  CHECKER_SUBMITTED_TOPIC_ADDRESS: {{ quote .Values.container.checkerSubmittedTopicAddress }}
  SERVICE_BUS_HOST: {{ .Values.container.messageQueueHost | quote }}
  NOTIFY_EMAIL_TEMPLATE: {{ .Values.container.notifyEmailTemplate | quote }}
{{- end -}}
