{{- include "ffc-helm-library.container-config-map" (list . "ffc-grants-eligibility-checker.config-map") -}}
{{- define "ffc-grants-eligibility-checker.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }} 
  SERVICE_BUS_HOST: {{ .Values.container.messageQueueHost | quote }}
  NOTIFY_EMAIL_TEMPLATE: {{ .Values.container.notifyEmailTemplate | quote }}
  NOTIFY_EMAIL_TEMPLATE: {{ quote .Values.container.notifyEmailTemplate | quote }}
  NOTIFY_EMAIL_ADDRESS: {{ quote .Values.container.notifyEmailAddress | quote }}
  SESSION_CACHE_TTL: {{ .Values.container.sessionCacheTTL | quote }}  
  USE_REDIS: {{ .Values.container.useRedis | quote }}
  REDIS_HOSTNAME: {{ .Values.container.redisHostname | quote }}
  REDIS_PORT: {{ .Values.container.redisPort | quote }}
  REDIS_PARTITION: {{ .Values.container.redisPartition | quote }}
  
{{- end -}}
