{{- include "ffc-helm-library.container-config-map" (list . "ffc-grants-eligibility-checker.config-map") -}}
{{- define "ffc-grants-eligibility-checker.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }} 
  SESSION_CACHE_TTL: {{ .Values.container.sessionCacheTTL | quote }}  
  USE_REDIS: {{ .Values.container.useRedis | quote }}
  REDIS_HOSTNAME: {{ .Values.container.redisHostname | quote }}
  REDIS_PORT: {{ .Values.container.redisPort | quote }}
  REDIS_PARTITION: {{ .Values.container.redisPartition | quote }}
  SERVICE_BUS_HOST: {{ quote .Values.container.serviceBusHost }}
  NOTIFY_SUBMIT_QUEUE: {{ quote .Values.container.notifySubmitQueue }}
  NOTIFY_EMAIL_TEMPLATE: {{ quote .Values.container.notifyEmailTemplate }}
  NOTIFY_EMAIL_ADDRESS: {{ quote .Values.container.notifyEmailAddress }}
  LOCAL: {{ quote .Values.container.local }}

{{- end -}}
