{{- include "ffc-helm-library.deployment" (list . "ffc-grants-eligibility-checker.deployment") -}}
{{- define "ffc-grants-eligibility-checker.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-grants-eligibility-checker.container") }}
{{- end -}}
